name: FTP Test

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: ./
        with:
          server: ftp.legenda.co
          username:  austin@legenda.co
          password: ${{ secrets.FTP_PASSWORD }}
